name: wtf_wikipedia

on:
  workflow_call: {}

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install dependencies
      run: |-
        sudo apt-get install jq moreutils
        npm install -g wtf_wikipedia@9.1.0
        curl -L https://github.com/every-politician-scrapers/shared/raw/main/bin/qsv -o /usr/local/bin/qsv
        chmod 755 /usr/local/bin/qsv
        curl -L https://raw.githubusercontent.com/every-politician-scrapers/shared/main/bin/wtf_enwiki.sh -o /usr/local/bin/wtf_enwiki.sh
    - name: Run mirroring
      run: |-
        rm -rf enwiki
        bash /usr/local/bin/wtf_enwiki.sh
    - name: Directly commit raw output
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add enwiki/wtf
        timestamp=$(date -u)
        git commit -m "Update wtf archive: ${timestamp}" || exit 0
        git push
    - name: Create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: wtf-wikipedia update
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: wtf
        delete-branch: true
        title: 'Update wtf_wikipedia mirror'
        assignees: tmtmtmtm
        reviewers: tmtmtmtm
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
